// supabase/functions/_shared/portalIdentifiers.ts
// Portal name -> reference-number label (e.g. "Bid No. (GeM)", "Tender ID"),
// mirrored from the PORTALS list in src/lib/portal_table.js. Duplicated
// here rather than imported because edge functions only deploy
// supabase/functions/** — anything under src/ isn't in the deploy bundle.
// Only the `identifier` field is needed for the Fee Note's "label of
// reference no. according to different portal selected in lead" — keep in
// sync with portal_table.js if a portal's identifier label changes there.

export const PORTAL_IDENTIFIERS: Record<string, string> = {
  "GeM (Government e-Marketplace)": "Bid No. (GeM)",
  "CPPP (Central Public Procurement Portal)": "Tender ID",
  "IREPS (Indian Railways)": "Tender No.",
  "MSTC e-Procurement": "Tender No.",
  "BHEL e-Procurement": "Tender Ref. No.",
  "NTPC e-Procurement": "Tender No.",
  "ONGC e-Procurement": "Tender No.",
  "Coal India e-Procurement": "NIT No.",
  "NABARD e-Procurement": "Tender No.",
  "NITI Aayog / DPIIT Portal": "Ref. / RFP No.",
  "NSDC (National Skill Development Corp.)": "Tender / RFP No.",
  "MoRD (Ministry of Rural Development)": "Tender No.",
  "Only NRLMs Portal": "Tender No.",
  "NHAI e-Procurement": "Tender No.",
  "NHIDCL e-Procurement": "Tender No.",
  "RITES e-Procurement": "Tender No.",
  "NBCC e-Procurement": "Tender No.",
  "CPWD e-Procurement": "NIT No.",
  "AIIMS Tenders": "Tender No.",
  "DRDO e-Procurement": "Tender No.",
  "MoEF&CC Tenders": "Tender No.",
  "SIDBI e-Procurement": "RFP No.",
  "Delhi e-Tendering": "NIT / Tender No.",
  "Maharashtra MahaTenders": "Tender No.",
  "UP eTender": "Tender No.",
  "Karnataka eProcurement": "Tender No.",
  "Tamil Nadu Tenders": "Tender No.",
  "Gujarat Tender": "Tender No.",
  "Rajasthan eProcurement": "Tender No.",
  "Madhya Pradesh Tenders": "Tender No.",
  "Himachal Pradesh Tenders": "Tender No.",
  "Uttarakhand Tenders": "Tender No.",
  "Punjab eProcurement": "Tender No.",
  "Haryana eProcurement": "Tender No.",
  "Bihar eProcurement": "Tender No.",
  "Odisha Tenders": "Tender No.",
  "Jharkhand Tenders": "Tender No.",
  "Chhattisgarh eProcurement": "Tender No.",
  "West Bengal Tenders": "Tender No.",
  "Assam Tenders": "Tender No.",
  "Kerala Tenders": "Tender No.",
  "Andhra Pradesh eProcurement": "Tender No.",
  "Telangana Tenders": "Tender No.",
  "Goa Tenders": "Tender No.",
  "J&K Tenders": "Tender No.",
  "Meghalaya Tenders": "Tender No.",
  "Manipur Tenders": "Tender No.",
  "Tripura Tenders": "Tender No.",
  "Nagaland Tenders": "Tender No.",
  "Mizoram Tenders": "Tender No.",
  "Arunachal Pradesh Tenders": "Tender No.",
  "Sikkim Tenders": "Tender No.",
  "Puducherry Tenders": "Tender No.",
  "Chandigarh Tenders": "Tender No.",
  "Ladakh Tenders": "Tender No.",
  "World Bank Projects (worldbank.org)": "Project ID",
  "ADB Projects (adb.org)": "Project No.",
  "UNDP Procurement (undp.org)": "RFP / ITB No.",
  "UN Global Marketplace (ungm.org)": "UNGM Ref. No.",
  "GIZ (Deutsche Gesellschaft)": "Tender Ref.",
  "JICA Projects": "Project / Bid No.",
  "USAID Procurement": "Solicitation No.",
  "KfW Development Bank": "Bid / RFP No.",
  "IsDB (Islamic Dev. Bank)": "IFB / RFP No.",
  "NDB (New Dev. Bank)": "Project / Bid No.",
  "AIIB Projects": "Project No.",
  "EU Tender (ted.europa.eu)": "Contract Notice No.",
  "AfDB (African Dev. Bank)": "Project / IFB No.",
  "EBRD Procurement": "Tender No.",
  "Tenderwizard": "Tender No.",
  "Bidassist": "Tender No.",
  "Tendersniper": "Tender No.",
  "eProcurement Technologies (ETL)": "Tender / Bid No.",
  "C1 India": "RFQ / RFP No.",
  "Private / Direct (Email / Newspaper)": "Ref. No. (if any)",
  "Direct from Client": "Ref. No. (if any)",
  "Newspaper Advertisement": "Ad Ref. / Date",
  "Industry Referral": "Ref. No. (if any)",
  "Other": "Ref. / ID No.",
};

export function portalRefLabel(portalName: string | null | undefined): string {
  if (!portalName) return "Reference No.";
  return PORTAL_IDENTIFIERS[portalName] || "Reference No.";
}
